data = [["Netherlands","Belgium"],
["Mexico","Canada"],
["Belgium","Belgium"],
["Belgium","Austria"],
["Mexico","Italy"],
["Australia","Mexico"],
["Italy","Canada"],
["Australia","India"],
["Canada","Austria"],
["France","Italy"],
["Austria","New Zealand"],
["Indonesia","Turkey"],
["Netherlands","Austria"],
["Germany","United Kingdom"],
["United States","Austria"],
["United States","Mexico"],
["New Zealand","Brazil"],
["Turkey","Turkey"],
["New Zealand","Canada"],
["Mexico","Mexico"],
["Italy","Italy"],
["Canada","France"],
["Netherlands","Netherlands"],
["India","Brazil"],
["Italy","Austria"],
["Austria","Netherlands"],
["Turkey","United Kingdom"],
["India","India"],
["Australia","Australia"],
["United States","Mexico"],
["Mexico","France"],
["India","New Zealand"],
["Australia","New Zealand"],
["Australia","Australia"],
["Indonesia","Netherlands"],
["Italy","Canada"],
["India","Belgium"],
["Australia","Netherlands"],
["Belgium","Austria"],
["Netherlands","Italy"],
["Italy","India"],
["India","Belgium"],
["Austria","Brazil"],
["Australia","Brazil"],
["Mexico","New Zealand"],
["Belgium","Netherlands"],
["Belgium","India"],
["France","India"],
["United States","United Kingdom"],
["United States","United Kingdom"],
["Turkey","Australia"],
["Austria","Australia"],
["Brazil","United Kingdom"],
["Belgium","Belgium"],
["United Kingdom","Canada"],
["Belgium","United Kingdom"],
["Italy","Netherlands"],
["Brazil","New Zealand"],
["Indonesia","United States"],
["Australia","Turkey"],
["Mexico","Austria"],
["Germany","Netherlands"],
["Indonesia","Italy"],
["United Kingdom","India"],
["Brazil","Brazil"],
["Austria","Italy"],
["Mexico","United Kingdom"],
["Canada","New Zealand"],
["Netherlands","Indonesia"],
["France","Germany"],
["United States","United Kingdom"],
["Netherlands","India"],
["Belgium","Austria"],
["Australia","Indonesia"],
["Indonesia","Canada"],
["United Kingdom","Belgium"],
["New Zealand","Brazil"],
["Indonesia","India"],
["United States","Brazil"],
["Brazil","Italy"],
["United Kingdom","Austria"],
["Australia","Austria"],
["Germany","Turkey"],
["Indonesia","Australia"],
["Belgium","United States"],
["Brazil","Germany"],
["Netherlands","Australia"],
["United States","Turkey"],
["Indonesia","India"],
["Turkey","Belgium"],
["Austria","Austria"],
["Belgium","United Kingdom"],
["Italy","Brazil"],
["New Zealand","Austria"],
["Turkey","Italy"],
["Netherlands","Mexico"],
["France","Australia"],
["Brazil","United States"],
["France","Germany"],
["United States","Mexico"]]